name: lenox
description: A simple static site generator writter in Dart
homepage: https://github.com/valajan/lenox
version: 0.0.1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  markdown: ^2.1.3
  process_run: ^0.10.6
  http_server: ^0.9.8+3
  mime_type: ^0.2.4
  args: ^1.5.2
  yaml_config: ^0.1.2
  mustache: ^1.1.1
  front_matter: ^1.1.0
  pedantic: ^1.9.0

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0

executables:
  lenox: lenox
