name: Lenox
author: Anthony Scheidler <s.anth@outlook.fr>
dependencies:
  markdown: ^2.1.3
  process_run: ^0.10.6
  http_server: ^0.9.8+3
  mime_type: ^0.2.4
dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0